### PR TITLE
Fix Comments

### PR DESCRIPTION
**Pull request by ksixen**
Hi, there, the comments on this library doesn't correctly placed

fix pls

image

### CODE REVIEW

**Comment by laki944** [comment]
Hi guys, it would be nice to merge this PR because this issue is a blocker for many people.

**Comment by knuula** [comment]
yes, please merge this PR! Can't really find a way around this right now.

**Comment by knuula** [comment]
if any of you has the ability to merge this PR, that would be wonderful! @andr83 @rlidwka

**Comment by puzrin** [comment]
1.  the second commit in this PR is not needed, because deviates style from original https://github.com/madler/zlib/blob/master/trees.c
2. Do all changes needed or only one, as in https://github.com/nodeca/pako/pull/261?
3. Please, do commit text more descriptive, to avoid confusion on resync with mainstream, Something like "Fix comments for Babel [version] compatibility" (or something like that)

**Comment by knuula** [comment]
@puzrin - I am not sure if the all of the changes in this commit are needed for the babel-loader issue. 

the change in #261 was the only thing causing the compile failures for me.

**Comment by knuula** [comment]
@puzrin - I take that back. My compiler was failing before it got to the later functions in trees.js

the changes in #263 are going to be needed as well.

**Comment by puzrin** [comment]
Let's stay with this things:

1. In trees.js Move `{` before comments in all such places
    - `npm test` - if linter shows error - add indent (2 spaces) to comment lines 
2. Update commit text (first line), to show explicit, this is js-specific thing and can be ignored on resync with zlib mainstream.

I can wait for PR or do that myself if you are busy.

Also please report bug to babel (or other appropriate tool) - it's important to fix the real source of such problem.

**Comment by knuula** [comment]
@puzrin - if you can do this, that would be great. I do not do PRs to third-party libraries very often, so I don't really know the proper protocol.

I will report the bug to babel. The issue came from **babel-loader@9.1.0**

Thank you very much for your help with all of this.

**Comment by puzrin** [comment]
@knuula could you check update in `master` before i do release?

**Comment by puzrin** [comment]
Released 2.1.0

**Comment by knuula** [comment]
@puzrin - awesome! thank you so much!

**Pull request closed without merging**
