### PR TITLE
Add Zlib license

### PR DESCRIPTION
**Pull request by renehamburger**
This corresponds to the `(MIT AND Zlib)` of the package.json.

### CODE REVIEW

**Comment by puzrin** [comment]
https://github.com/nodeca/pako/tree/master/lib/zlib it already exists.

**Comment by renehamburger** [comment]
Yes, I saw that, as well as the copyright notices in each zlib source file. My difficulty is that the license identifier used in the package.json `(MIT AND Zlib)` does not match the license of the single [LICENSE file](https://github.com/nodeca/pako/blob/master/LICENSE) contained in your repository.

**Comment by puzrin** [comment]
I think, if one of Debian maintainers was satisfied with result, that's enough.

**Comment by renehamburger** [comment]
Thanks for the clarification!

**Pull request closed without merging**
