### PR TITLE
Rename module build .js => .mjs to fix node import

### PR DESCRIPTION
**Pull request by IgorNovozhilov**
https://github.com/nodeca/pako/issues/199

### CODE REVIEW

**Comment by puzrin** [comment]
IMO second commit is no necessary. I's better to add `module` entry for some bundles. Also please remove `dist/`

PS. Or just wait couple of hours, i will do everything myself.

**Comment by IgorNovozhilov** [comment]
@puzrin re-commit

**Comment by IgorNovozhilov** [comment]
I think you need 2 libraries.
`pako.esm.js` - for browser use
`pako.esm.mjs`  - for Node.JS use
> At least if there is no full `"type": "module"` yet

**Comment by puzrin** [comment]
I think browsers will eat mjs or es5. Or we can add .js module later on demand. I'd like to avoid files count growth in dist. Just rename in rollup .js => .mjs

**Comment by IgorNovozhilov** [comment]
> Or we can add .js module later on demand.

OK, I checked Chrome and Firefox. I have my doubts about Safari, but I have no place to check.

**Pull request merged**
