### PR TITLE
Benchmark update

### PR DESCRIPTION
**Pull request by desudesutalk**
Benchmark of zlib was implemented in async manner. This was true for node.js before v0.11.12 because there was no Sync variants of functions.

In latest node.js versions this affects benchmark because other libraries are called synchronously without any overhead of streamed data processing and buffer concatenations.

### CODE REVIEW

**Comment by puzrin** [comment]
While idea to use new zlib.sync is really good, i don't like how results are implemented:

1. There is no compare of zlib sync/async. I guess, result for deflate should be the same.
2. Replacing benchmarks with one from your cpu is not enougth:
    - Result of run BEFORE change is not shown. It's impossible to compare, what was affected.
    - I think, it will be better if results in readme will be updated by me. Because i will be able to rerun when needed.
    - Specially for deflate, it worth to run in 4, 6, 8 node.js, because result may vary on v8 engine.

I'd suggest to post here results of described benchmarks, and then we decide how to update this PR.

**Comment by desudesutalk** [comment]
My results with unmodified benchmarks:

```
node v0.10.26, 1mb sample:

 > deflate-imaya x 4.04 ops/sec ±3.36% (14 runs sampled)
 > deflate-pako x 8.92 ops/sec ±0.18% (25 runs sampled)
 > deflate-pako-string x 7.45 ops/sec ±0.73% (22 runs sampled)
 > deflate-pako-untyped x 5.31 ops/sec ±1.32% (17 runs sampled)
 > deflate-zlib x 14.62 ops/sec ±4.49% (74 runs sampled)
 > inflate-imaya x 39.94 ops/sec ±2.16% (50 runs sampled)
 > inflate-pako x 85.64 ops/sec ±2.51% (69 runs sampled)
 > inflate-pako-string x 22.31 ops/sec ±0.96% (40 runs sampled)
 > inflate-pako-untyped x 19.50 ops/sec ±0.54% (57 runs sampled)
 > inflate-zlib x 220 ops/sec ±5.31% (72 runs sampled)

node v0.11.12, 1mb sample:

 > deflate-imaya x 4.17 ops/sec ±4.43% (14 runs sampled)
 > deflate-pako x 13.94 ops/sec ±0.38% (37 runs sampled)
 > deflate-pako-string x 11.39 ops/sec ±1.40% (32 runs sampled)
 > deflate-pako-untyped x 6.24 ops/sec ±1.10% (20 runs sampled)
 > deflate-zlib x 18.58 ops/sec ±1.75% (83 runs sampled)
 > inflate-imaya x 93.17 ops/sec ±0.34% (74 runs sampled)
 > inflate-pako x 117 ops/sec ±0.87% (70 runs sampled)
 > inflate-pako-string x 55.64 ops/sec ±2.15% (62 runs sampled)
 > inflate-pako-untyped x 28.33 ops/sec ±1.12% (48 runs sampled)
 > inflate-zlib x 168 ops/sec ±6.03% (71 runs sampled)

node v8.1.3, 1mb sample:

 > deflate-imaya x 4.83 ops/sec ±1.62% (16 runs sampled)
 > deflate-pako x 12.28 ops/sec ±0.27% (33 runs sampled)
 > deflate-pako-string x 10.45 ops/sec ±0.48% (29 runs sampled)
 > deflate-pako-untyped x 7.07 ops/sec ±0.59% (21 runs sampled)
 > deflate-zlib x 10.98 ops/sec ±8.14% (60 runs sampled)
 > inflate-imaya x 90.50 ops/sec ±2.22% (69 runs sampled)
 > inflate-pako x 96.05 ops/sec ±1.83% (71 runs sampled)
 > inflate-pako-string x 60.19 ops/sec ±1.28% (58 runs sampled)
 > inflate-pako-untyped x 22.67 ops/sec ±1.03% (39 runs sampled)
 > inflate-zlib x 88.84 ops/sec ±8.35% (49 runs sampled)
```

**Comment by puzrin** [comment]
Could you post a bit different things?

1. Results before change for node 4, 6, 8
2. Results after change for node 4, 6, 8

All in one post.

**Comment by desudesutalk** [comment]
Here we go

Before changes:

```
node v4.8.4, 1mb sample:

 > deflate-imaya x 3.97 ops/sec ±3.01% (14 runs sampled)
 > deflate-pako x 14.27 ops/sec ±0.24% (38 runs sampled)
 > deflate-pako-string x 10.07 ops/sec ±0.50% (28 runs sampled)
 > deflate-pako-untyped x 7.37 ops/sec ±0.58% (21 runs sampled)
 > deflate-zlib x 11.23 ops/sec ±6.43% (54 runs sampled)
 > inflate-imaya x 95.00 ops/sec ±0.66% (72 runs sampled)
 > inflate-pako x 104 ops/sec ±1.37% (73 runs sampled)
 > inflate-pako-string x 40.08 ops/sec ±1.02% (57 runs sampled)
 > inflate-pako-untyped x 42.30 ops/sec ±1.62% (56 runs sampled)
 > inflate-zlib x 218 ops/sec ±9.82% (63 runs sampled)

node v6.11.1, 1mb sample:

 > deflate-imaya x 4.90 ops/sec ±1.65% (16 runs sampled)
 > deflate-pako x 11.96 ops/sec ±0.49% (33 runs sampled)
 > deflate-pako-string x 10.09 ops/sec ±0.45% (28 runs sampled)
 > deflate-pako-untyped x 6.94 ops/sec ±1.19% (21 runs sampled)
 > deflate-zlib x 19.14 ops/sec ±7.83% (61 runs sampled)
 > inflate-imaya x 86.26 ops/sec ±1.22% (65 runs sampled)
 > inflate-pako x 118 ops/sec ±1.44% (71 runs sampled)
 > inflate-pako-string x 22.28 ops/sec ±1.61% (39 runs sampled)
 > inflate-pako-untyped x 24.91 ops/sec ±1.91% (46 runs sampled)
 > inflate-zlib x 89.00 ops/sec ±10.67% (47 runs sampled)

node v8.1.3, 1mb sample:

 > deflate-imaya x 4.81 ops/sec ±1.71% (16 runs sampled)
 > deflate-pako x 12.26 ops/sec ±0.30% (33 runs sampled)
 > deflate-pako-string x 10.23 ops/sec ±0.49% (29 runs sampled)
 > deflate-pako-untyped x 7.23 ops/sec ±0.83% (21 runs sampled)
 > deflate-zlib x 8.36 ops/sec ±7.97% (50 runs sampled)
 > inflate-imaya x 72.56 ops/sec ±2.21% (68 runs sampled)
 > inflate-pako x 122 ops/sec ±1.76% (70 runs sampled)
 > inflate-pako-string x 58.32 ops/sec ±1.19% (67 runs sampled)
 > inflate-pako-untyped x 22.66 ops/sec ±1.05% (39 runs sampled)
 > inflate-zlib x 101 ops/sec ±8.37% (51 runs sampled)
```

After:

```
node v4.8.4, 1mb sample:

 > deflate-imaya x 3.88 ops/sec ±3.42% (13 runs sampled)
 > deflate-pako x 14.04 ops/sec ±0.26% (37 runs sampled)
 > deflate-pako-string x 9.97 ops/sec ±0.23% (28 runs sampled)
 > deflate-pako-untyped x 7.13 ops/sec ±0.77% (21 runs sampled)
 > deflate-zlib x 19.15 ops/sec ±0.22% (49 runs sampled)
 > inflate-imaya x 91.71 ops/sec ±0.96% (70 runs sampled)
 > inflate-pako x 110 ops/sec ±1.58% (71 runs sampled)
 > inflate-pako-string x 44.94 ops/sec ±1.20% (56 runs sampled)
 > inflate-pako-untyped x 44.25 ops/sec ±1.96% (56 runs sampled)
 > inflate-zlib x 269 ops/sec ±1.57% (78 runs sampled)

node v6.11.1, 1mb sample:

 > deflate-imaya x 4.97 ops/sec ±1.65% (16 runs sampled)
 > deflate-pako x 12.14 ops/sec ±0.21% (33 runs sampled)
 > deflate-pako-string x 10.04 ops/sec ±0.57% (28 runs sampled)
 > deflate-pako-untyped x 7.13 ops/sec ±0.74% (21 runs sampled)
 > deflate-zlib x 19.79 ops/sec ±0.20% (35 runs sampled)
 > inflate-imaya x 86.53 ops/sec ±0.99% (67 runs sampled)
 > inflate-pako x 120 ops/sec ±1.17% (71 runs sampled)
 > inflate-pako-string x 20.05 ops/sec ±1.73% (38 runs sampled)
 > inflate-pako-untyped x 27.85 ops/sec ±1.28% (46 runs sampled)
 > inflate-zlib x 249 ops/sec ±1.82% (78 runs sampled)

node v8.1.3, 1mb sample:

 > deflate-imaya x 4.79 ops/sec ±1.56% (16 runs sampled)
 > deflate-pako x 12.10 ops/sec ±0.22% (33 runs sampled)
 > deflate-pako-string x 10.19 ops/sec ±0.51% (29 runs sampled)
 > deflate-pako-untyped x 7.16 ops/sec ±0.76% (21 runs sampled)
 > deflate-zlib x 19.96 ops/sec ±0.32% (36 runs sampled)
 > inflate-imaya x 90.76 ops/sec ±1.92% (69 runs sampled)
 > inflate-pako x 115 ops/sec ±1.74% (69 runs sampled)
 > inflate-pako-string x 59.67 ops/sec ±1.07% (58 runs sampled)
 > inflate-pako-untyped x 22.59 ops/sec ±0.97% (39 runs sampled)
 > inflate-zlib x 266 ops/sec ±2.20% (77 runs sampled)
```

**Comment by puzrin** [comment]
Ok, result seems to behave as expexted:

- not changed too much (become more stable) for deflate
- affected inflate. But since inflate has significant dependency on memory copy and objects marshaling, it was never concidered as something trusted (or as way to measure JS speed)

I suggest to finalize with this:

- Replace content of zlib inflate/deftate with your new code and don't touch anything else.

Then i'll accept PR and update readme ewith new data.

**Comment by desudesutalk** [comment]
Should `benchmark.js` be updated? Without node version check it will fail on v0.10

**Comment by puzrin** [comment]
> Without node version check it will fail on v0.10

Not needed. 0.10 is not supported anymore.

**Comment by desudesutalk** [comment]
Now looks OK.

**Comment by puzrin** [comment]
Merged. Sorry for delay, i had to check what's up with tests to make CI work again.

**Pull request merged**
