### PR TITLE
converted most things to classes

### PR DESCRIPTION
**Pull request by jimmywarting**
Modernization

### CODE REVIEW

**Comment by puzrin** [comment]
I don't see reasons in changes "just for fun". This does not seems to improve anything.

**Comment by jimmywarting** [comment]
😞

**Comment by jimmywarting** [comment]
btw, i where going to use pako and wanted to use a esm build with `<script type="module">` and `import` but the only option i found was `/npm/pako@2.0.4/dist/pako.esm.mjs` (found in: https://www.jsdelivr.com/package/npm/pako?path=dist)

But it's not minimized and it's not code splited. I only needed the inflate. but i can't `import` the inflate cuz it's in cjs/umd

It would be grate if this lib was built using import instead and compiled down to cjs so it could be possible to use the original source from the src lib directly.

**Comment by puzrin** [comment]
I'm not ready to change development process. AFAIK, if you use `.mjs` with inflate only + something like webpack, tree shaker should drop all unused code. That's why mjs build has no variants.

**Comment by codedread** [comment]
I'd like to point out that this kind of modernization really improves things in modern IDEs (like VS Code), it's not just "for fun". This is what I get when I turn DeflateState into a class and update the comments to be jsdoc:

image

(Mind you, I do not understand the development process, I know you must be tying things to zlib C project pretty closely)

**Comment by puzrin** [comment]
@codedread IMO there are no need for such changes, until you really wish to debug/develop this package in your IDE. I could agree with dev process changes if someone really wish to fix existing issues.

**Pull request closed without merging**
