### PR TITLE
Add E6 modules support

### LINKED ISSUE #97: Include es6 module support
All modern browsers now support es6 modules (except chrome which will land shortly).

Could you include an es6 module version of pako?

### PR DESCRIPTION
**Pull request by juanjoDiaz**
This is just an initial commit for you to see the approach before I spend time in something that you don't like, @puzrin .

With the new change, Rollup produces 3 bundles:
- CommonJS
- UMD
- ES6 module

`package.json` now exposes those 3 packages so most bundlers and libraries can choose to pull the better version.

This removes the need for browserify and rollup should be much more lightweight.

I can easily produce also 3 minimized bundles.
Also, I wasn't sure why Inflate and deflate where packaged independently. But I can also add those 2 with the 3 modules.

This also open the door to use ES6 and more modern JS features and have rollup to produce a ES5 bundle using babel for example.

Wdyt??

Closes #97

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
Currently, you expose `pako`, `pako_deflate` and `pako_inflate` plus the minified versions (`pako.min`, `pako_deflate.min` and `pako_inflate.min`). 3 in total.

Those are browserified modules. i.e. modules that register `pako` to the global scope.

The proposal is to have 3 separate modules:
- *ES6* as requested in #97 and what I really need (`.esm.js`, to be renamed to `.mjs` following Node.js 11)
- *Common.js* technically not necessary since pako uses it already so you could use its index file (`.cjs.js`)
- *UMD (Universal Module Definition)* Like browserify but works also with AMD and CommonJS system (`.umd.js`).

You need the extra files in dist at least for ES6 modules, there is no way around that.
CommonJS and UMD could use the existing files and simply use UMD.

In any case, that would be: `pako`, `pako_deflate` and `pako_inflate` x 3 modules + minified (x2) = 18 files in dist (9 if we merge cjs and umd).
I can totally do it. But seems like a lot which is why I was asking if it's needed to have all those.

Specially since:
- Most bundlers do tree shaking (making `pako_deflate` and `pako_inflate` unnecessary) and minification (making all the minified files obsoletes).
- Pupular CDNs like jsDelivr can automatically minify the code they deliver. For example: https://cdn.jsdelivr.net/npm/json2csv@4.2.1

**Comment by puzrin** [comment]
Prior to discuss any proposals, i'd like to understand what's wrong right now. You said before about some problems with rollup, but i do not understand which problems do you mean.

**Comment by juanjoDiaz** [comment]
The problem is not Rollup specific.
The problem is that you only support CommonJs (index.js) and global scope (browserified dist).

The excludes anyone using AMD or ES6 imports, for example.

Rollup is just a concrete example of using ES6 imports.

Another problem is that, because of the way that you do exports in pako assigning the exports from inflate and deflate to an object, ES6 exports can't be inferred (which is why in this PR I had to set them up manually in the rollup config) and stuff like tree shaking probably won't work.

Summarizing: Pako doesn't use modern javascript and doesn't integrate well with them. Which leads to people having to manually copy and modify pako instead of being able to import it and bundle it using modern technologies (e.g.: https://github.com/novnc/noVNC/tree/master/vendor/pako)

**Comment by juanjoDiaz** [comment]
Hi @puzrin ,

I'd appreciate a bit more constructive feedback instead of negative empty comments.
If you don't want this contribution, just say it and I'll drop it. No hard feelings. 🙂 

Your requirements were:
* is compatible with both modules & commonjs
* still keeps /dist structure (es5)
* works in latest node natively (for development) and in older node after transpile / npm publish

The proposed solution:
* is compatible with modules, commonjs and UMD
* can keep the `/dist`folder structure (I've updated the commit so you see it. I can add the minified versions if you want them, although, as I showed to you before CDNs can minify by default making it unnecessary).
* Doesn't touch the existing codebase at all, so it works as it does now in node.

What is exactly what I have ignored from #97?
What exactly would you like to be different?

P.S.: I still have some clean up to do in the PR. This is just for you to see it and give your opinion.

**Comment by puzrin** [comment]
The main point of #97 was:

- number or transpiled files should be minimal and not touch development process
- if we need "modern JS support" - we should use it natively, instead of transpilers
- no breaking things
- native node support for both `require` & `import`

That means:

- if sources can be in es6 - no es6 builds in `/dist` required.
- package.json should be enougth for node.js & any bundler to select proper code version
- `/dist` file names should not be changed without strong reasons.

**Comment by puzrin** [comment]
Also, a side note - PR title should be more precise about goal/intent. Pako does not need "rollup bundling". It needs "es6 modules support".

**Comment by juanjoDiaz** [comment]
Alright, thanks for the comments. Let me try to answer them:

At the moment we aren't using any transpilation. Rollup simply replaces `module.export/exports` and `require` with ES6 `export` and `import`. Nothing else is changed in the code.

`package.json` is enough indeed to select the right format. That's already done in this PR.

The filenames in `dist` haven't changed at all with my latest commit.

There are no breaking changes (except the missing minified versions, which, as said, can be added any time. You still haven't comment on this and my point that they aren't really needed).

I can modify the sources to be ES6 and the commonjs to be bundled in the dist folder if you prefer that. Just let me know. However, all node versions support commonjs, node 11 with an experimental flag enabled support ES6 modules. Furthermore `require` won't work with ES6 modules but `import` will work with cjs modules. So we still need to set the commonjs version as `main` for maximun compatibility.



So from my point of view, there are 2 open questions:
- Is it necessary (or desired) to keep the minified versions?
- Is it OK to have the sources in cjs and a es6 modules in the `dist` folder? Or would you prefer to have the library in ES6 and commonjs as a bundle in `dist`?

Is there anything else that I'm missing?

**Comment by juanjoDiaz** [comment]
Ok I was reading more about this, and node's resolution algorithm is smart enough to distinguish ES6 from cjs if you just skip the extension in package.json. So I can do the change. Although this PR is going to get much bigger 🙂 

Other question, since `dist` only contains generated files.
Is it necessary to have them committed in the repo?
Would it be ok to git-ignore them, and just generate them when releasing?

**Comment by juanjoDiaz** [comment]
Btw, changing to ES6 might be a rather large rewrite since you seem to use dynamic exports which won't work as ES6 modules.

Like
```js
exports.setTyped = function (on) {
  if (on) {
    exports.Buf8  = Uint8Array;
    exports.Buf16 = Uint16Array;
    exports.Buf32 = Int32Array;
    exports.assign(exports, fnTyped);
  } else {
    exports.Buf8  = Array;
    exports.Buf16 = Array;
    exports.Buf32 = Array;
    exports.assign(exports, fnUntyped);
  }
};
```

or

```js
var pako = {};

assign(pako, deflate, inflate, constants);

module.exports = pako;
```

**Comment by puzrin** [comment]
> Btw, changing to ES6 might be a rather large rewrite since you seem to use dynamic exports which won't work as ES6 modules.

Then possible workarounds should be found/discussed. Doing es6 via es5 is kludge by design. I don't like to keep such things if development process changed. Only when no other acceptable choice possible.

**Comment by puzrin** [comment]
Hm... forgot to mention. Some people use `/lib/zlib` content directly. We should keep it available for old (es5) node too, if people wish to `require()` files directly.

**Comment by juanjoDiaz** [comment]
In that case, lib must be kept as ES5 and the current approach seems correct.

> Doing es6 via es5 is kludge by design. I don't like to keep such things if development process changed. Only when no other acceptable choice available.

Can you elaborate a bit on this? I'm not sure what are you referring to.
The proposed approach doesn't require any change in the development process as far as I can see.

**Comment by puzrin** [comment]
> Can you elaborate a bit on this? I'm not sure what are you referring to.

If sources are in es5, people will cry that tree shaking is not supported.

Please, move the rest of questions to #97. Information become too fragmented between multiple threads. That's not convenient.

**Comment by juanjoDiaz** [comment]
So, regarding https://github.com/nodeca/pako/pull/149#issuecomment-445536126

Is it Ok to drop the fallback and simply use TypedArrays?
They are supported in all major browsers and in node since 4.X (which is already deprecated)

Also, Why `Uint8Array` and `Uint16Array`, but `Int32Array` why is the 32 bit array signed?

**Comment by juanjoDiaz** [comment]
Alright!
1. The whole library is now ES6 modules.
2. Rollup is used to generate UMD and CommonJS modules (including minified versions).
3. Browserify has been removed since rollup replaces it.

I think that complies with all the requirements 🙂 
How does it look like?

**Comment by juanjoDiaz** [comment]
> Why dist contains .cjs.js files? It should be for legacy only (bower etc).

As I already explained, Node.js only supports ES6 using an experimental flag for now.
So cjs is needed to maximize support.
That's why I liked better the option of keeping the library as cjs for now and just have an ES6 bundle in dist.
In any case, ES6 is not just about node. It's about the browsers and about the tooling.

> Why benchmark includes src via hardcoded path instead of package.json in index?

That's how it was before. I simply updated it to point to the cjs bundle instead of the ES6 module.

> Now after every change, even in es6, developper has to recompile sources to run benchmark, for example (even in modern node). If development process changes required for es6 support, that should not be ass pain for developpers.

As said, modern node won't help here.
Developers can run `npm run dev` which will watch the sources and rebuild automatically when there are changes. So no need to be recompiling all the time.

> How can user access low level zlib api directly (from both old and new nodes)?

Users can in EC6 but not in cjs.
Once again, that's why I preferred cjs for the lib and ES6 support as a bundle.
An alternative is to not use rollup at all and simply use bable to generate a cjs equivalent of the ES6 code without bundling (maintaining the structure). Would you prefer this?

> (!) Dropped typed arrays checks are wrong, new code should not work in es6. I suspect it has not been tested in that mode.

Do you mean dropping the untyped arrays (`Array`) support?
I explained it before that ES6 doesn't support conditional import/export and TypedArrays work in all major browsers and node versions.
If for whatever reason user want to use node 0.10 or something like that he just need to do:
```js
global.Uint8Array = Array
global.Uint16Array = Array
global.Uint32Array = Array
```

Or do it properly and add a polyfill like https://github.com/inexorabletash/polyfill/blob/master/typedarray.js

> what about benchmark scores? Are those the same or not?

Yeah, they seem around the same. There haven't really been code changes.

> test files have huge diffs just because of var names change. Is this really necessary?

Yes. In ES6 you have multiple exports and you import them individually.
That's how, for example, rollup do tree shaking.

> It was not good idea to silently drop tests for ordinary arrays.

Look at my answer few lines above and my previous comment about typed arrays.
The problem is dynamic imports. The solution for whoever this is a problem (that should be no one) is to simply polyfill TypedArrays using standard Arrays or a more complete poly.

I tried to maintain the tests by overriding the default TypedArrays as in the old version but modern V8 engine doesn't let you simply override those classes.


So... how would you like me to proceed?
Full clone of the ES6 `lib` folder in commonjs so the users can import the low-level API from commonjs?
What about the `TypedArray` vs `Array`?
Anything else?

**Comment by puzrin** [comment]
> So... how would you like me to proceed?

I strongly recommend go to #97, define list of proposed changes and discuss those prior to do anything. Your current approach requires code review and is very time-consuming. I postponed es6 support not because i don't like it, but because i don't know way how to do this good enougth for all.

**Comment by puzrin** [comment]
I'm in process of migrating to rollup, es6 and so on.

Could you clarify, why your rollup config produces both umd and cjs? AFAIK umd can be used as cjs.

**Comment by juanjoDiaz** [comment]
Took you long enough to accept that this had to be done.
Not very nice to ignore my work and simply decide to reimplement it yourself, though

UMD can be used as CJS. But it adds an unnecessary layer to the import which can be skipped when you know that the target system uses CJS, as in node.

Feel free to close this PR if that's the case.

**Comment by puzrin** [comment]
Thanks for comment.

Sorry for not acepting your work "as is". There many small details to care or to make a bit different. I'd like to have progressive track in commits history to be sure nothing missed.

**Comment by puzrin** [comment]
One more question. Can you demand be solved by add `esm` output to rollup, but without sources update to import/export? Something like this https://github.com/nodeca/image-blob-reduce/pull/16/files

**Comment by juanjoDiaz** [comment]
There is no point on rolling up the sources if they are already in a valid format... You could just point your package.json to the index file. Or maybe I missed your point..

**Comment by puzrin** [comment]
My question is, what if i keep sources in cjs and transpile to module via rollup? Then add package.json `.module` entry for bunlers (`.export` seems not supported well).

**Comment by puzrin** [comment]
Created sample branch, see this diff https://github.com/nodeca/pako/commit/a6c8622bedec6bd51694f887c73388ae57d3c8ec

**Pull request closed without merging**
